/* automatically generated by rust-bindgen 0.60.1 */

extern "C" {
    #[link_name = "\u{1}_Z14facedetect_cnnPhS_iii"]
    pub fn facedetect_cnn(
        result_buffer: *mut ::std::os::raw::c_uchar,
        rgb_image_data: *mut ::std::os::raw::c_uchar,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
        step: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_int;
}
